name: Check
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm build

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Check formatting
        id: format
        run: pnpm format:check
        continue-on-error: true
      - name: Lint Code
        id: lint 
        run: pnpm lint
        continue-on-error: true
      - name: Check if any step failed
        if: steps.format.outcome == 'failure' || steps.lint.outcome == 'failure'
        run: |
          echo "::error::One or more code quality checks failed"
          exit 1

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm test
        env:
          NODE_OPTIONS: --max_old_space_size=8192

  integ:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: postgres:15.2-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm --filter @org/server db:migrate
      - run: pnpm test:integ
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/testdb
          NODE_OPTIONS: --max_old_space_size=8192
          NODE_ENV: development
