name: Deploy AWS Infra
on:
  workflow_run:
    workflows: [Check]
    types:
      - completed
  push:
    branches: [main]
    paths:
      - 'packages/infra/**'
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  deploy:
    name: Deploy AWS Infra
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::575108949460:role/any-thought-production-github
          aws-region: us-west-2
      - name: CDK Deploy
        run: pnpm --filter @org/infra deploy:prod
